Gemfile.lock, app/models/dog.rb, app/models/user.rb, db/migrate/20210301163034_create_dogs.rb, db/schema.rb, test/models/dog_test.rb
For the first step I just created all models ...
=> Add Dog model

app/models/message.rb, db/schema.rb
I added a validation to the message-model
=> added a message validation

app/channels/chatroom_channel.rb, app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/javascript/channels/chatroom_channel.js, app/models/message.rb, app/views/chatrooms/show.html.erb, app/views/messages/app:views:messages:_message.html.erb, config/cable.yml, config/routes.rb, db/migrate/20210302141650_add_user_to_messages.rb, db/schema.rb, test/channels/chatroom_channel_test.rb, test/controllers/chatrooms_controller_test.rb, test/controllers/messages_controller_test.rb
I created the user chat ... after talking to alex, it was neccessary to ad a column to the messages model to make a connection to the user
=> Create user chat

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_status.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/controllers/pages_controller.rb, app/models/dog.rb, app/models/park.rb, app/views/components/_card_dog.html.erb, app/views/pages/home.html.erb, db/schema.rb
I added the home page with following behaviour:
- login required for home page
- home page shows all the parks of the current_user's first dog
- each park shows all dogs in that park
Addtional 
- Added card and status component
- status component is still 'dumb' and has no ability to change
=> As a user i can visit the home page

app/javascript/packs/application.js
I fixed it - so it should autorefresh now
=> fixed the autrefresh

app/views/pages/home.html.erb
Just changed the title -home- to Doggies near you - ready to play
=> changed the title of the homepage

app/controllers/chatrooms_controller.rb, config/cable.yml
I just changed 2 little things here to fix the problem ... was not able to test it finally - because im never in the same park with both users ...
=> Chatroom fix

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_toggle.scss, app/controllers/dogs_controller.rb, app/controllers/users_controller.rb, app/javascript/components/toggle.js, app/javascript/packs/application.js, app/views/components/_card_dog.html.erb, app/views/components/_card_dog_small.html.erb, app/views/dogs/show.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20210308095505_add_read_to_walk_to_dogs.rb, db/schema.rb, db/seeds.rb
Behaviour:
1. User clicks on 'ready to walk' button in his dog profile page and changes the ready to walk status to true. Clicking again will remove the ready to walk status
2. The ready to walk tag is shown dogs#index, dog#show, sniffs#index, chatroom#id
Next ideas:  Dogs in the home page are sorted by the 'ready to walk' status
=> Toggle 'Ready to walk' status on the for each dog on the user show page

app/assets/stylesheets/dogs/_discover.scss, app/assets/stylesheets/dogs/_index.scss, app/controllers/dogs_controller.rb, app/views/dogs/discover.html.erb, app/views/shared/_bottom-navbar.html.erb, app/views/sniffs/index.html.erb, config/routes.rb
did the routes - the controller and the view and finally added a link to the footer
=> Discover page

app/assets/stylesheets/application.scss, app/views/pages/home.html.erb
I changed the title of the homepage, cause they asked for that in the feedback
=> changed title of the homepage

app/assets/stylesheets/chatrooms/_index.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_cards.scss, app/controllers/chatrooms_controller.rb, app/views/chatrooms/index.html.erb, app/views/components/_card_chatroom.html.erb, app/views/shared/_navbar-top-chatroom.html.erb
=> refactor @chatrooms controller and make Frontend for chatrooms#index

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/sniffs_controller.rb, app/models/sniff.rb, app/models/user.rb, app/views/shared/_navbar-top.html.erb, db/migrate/20210309164640_unread_migration.rb, db/schema.rb
User has list of other dogs sniffing his
-> show red dot if at least one unread sniff
-> hide red dot if user visits sniff page
=> View unread sniffs red dot

app/assets/stylesheets/components/_cards.scss, app/views/components/_card_dog_small.html.erb
=> The dog sniff index page has now picture for each dog in the card

app/assets/stylesheets/parks/_infowindow.scss, app/views/parks/_infowindow.html.erb
- changed the text/ the hover effect and the size of the image in the popup-window
=> style for the popup-window of the map

app/assets/stylesheets/dogs/_discover.scss, app/controllers/sniffs_controller.rb, app/views/dogs/discover.html.erb
- align the headline
- changed color and wording of the button 
- aligned the buttons
- cleaned the code
=> Discover page to style

app/assets/stylesheets/dogs/_edit.scss, app/assets/stylesheets/dogs/_index.scss, app/controllers/dogs_controller.rb, app/views/dogs/edit.html.erb
Gave it an basic app layout - was unable to change the fotobutton ...
=> Dog profile page style

app/views/shared/_navbar-top-chatroom.html.erb, app/views/shared/_navbar-top-dog-profile.html.erb
It isn't perfect because if the user click before to sniff/unsniff then the user has to click two times on the back button but as a quick fix should be ok for the demo
=> Add Javascript onclick function to the back button on the dog-profile navbar

app/views/dogs/show.html.erb
=> Add some margin between the bio and the breed (dogs#show)

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_upload-button.scss, app/views/dogs/edit.html.erb
=> Changed the style for the upload button on the edit dog profile

app/assets/stylesheets/registrations/_edit.scss, app/assets/stylesheets/users/_edit.scss, app/assets/stylesheets/users/_index.scss, app/controllers/users_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/shared/_bottom-navbar.html.erb
=> Update user profile

app/assets/stylesheets/registrations/_edit.scss, app/views/devise/registrations/edit.html.erb
=> Add margin bottom and changed the style of the upload button for the users#edit page

app/assets/stylesheets/users/_show.scss, app/controllers/dogs_controller.rb, app/views/users/show.html.erb
I styled the userpage and fixed the jumping bug
=> Userpage more final style and fix of the jump

app/views/dogs/discover.html.erb
I just commented in the link - to make the image on the dog-card clickable again ... (take at look at the read-to-walk-button - it moved)
=> discover page image is clickable again

public/500.html
=> styled the 500 page

app/views/pages/home.html.erb
=> Add condition for the H1 on the home page when the user has no dog yet

app/assets/stylesheets/registrations/_create.scss, app/assets/stylesheets/registrations/_index.scss, app/views/devise/registrations/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/dogs/edit.html.erb
=> styled the sign up page
